### ISSUE TITLE
differences between previous plots and current plots

### ISSUE THREAD

**Issue by mnky9800n** [mnky9800n/ECLASS-Report-Generator#12]
- The values and shift that I am seeing on this AppState report and the one Ben sent before are not the same.  Do you know why this might be?

**Comment by mnky9800n** [comment]
I think there are several issues going on here:
- When you calculate a confidence interval it shifts the origin as well, (see the docstring for `UtilitiesForPlotting.ConfidenceInterval`). I'm not sure Ben accounted for this in the original legacy code (it's in the master branch so we can check)
- I recall being told that the colors were switched for the Ben reports, thus "your class" is actually "Similar level classes" 

Do you see any major differences? It all looks like small shifts due to the confidence interval calculation to me.

**Comment by wilcoxbeth** [comment]
I accounted for the coloring issue when comparing the reports.  

Oh I see, I do seem to recall the differences were small.  This is actually something I have been meaning to ask you about.  I don't understand why the confidence interval calculation shifts the origin.  I see that it does, but I don't see why, from a fundamental standpoint, we would want it to do this.  It is not clear to me from either the docstring or the original slides.

**Comment by mnky9800n** [comment]
I emailed the author of the slides I used. This was his response:

> The shift is necessary to achieve the necessary coverage properties.  That is, to achieve the desired confidence.
> 
> Note that I can’t take any credit for the result.  I simply took if from:
> 
> Goodman, L.A. (1965). On Simultaneous Confidence Intervals for Multinomial Proportions, Technometrics, 7, 247-254.

**Comment by wilcoxbeth** [comment]
Ok, so I looked closely at that paper, and it turns out it is just modifying a formula originally derived in this paper:

Quesenberry, C. P., and D. C. Hurst. "Large sample simultaneous confidence intervals for multinomial proportions." Technometrics 6.2 (1964): 191-195.

Looking at that second paper, they make no conceptual argument why the origin shifts; it just seems to come out of the math.  I am generally ok with this, but I am still a little disturbed that this seems to produce nonsensical results sometimes (e.g., the issue with Q40 not showing up as 100% favorable even though it is).  It may be that this stems from the fact that this expression for the confidence interval assumes large enough N.  The paper above suggests no less than N=5 in the smallest bin.  This would seem to imply that the formula will break down in cases where N is small (or zero).  

Thoughts?

**Comment by mnky9800n** [comment]
I personally believe that courses that don't have matched data for at least 5 students (maybe even 10) should be dropped for the individual reports. You can aggregate these people later for research but I'm not sure what to make of a class that might have 20 enrolled that only 3 respond to the survey. I feel like it might be disingenuous to be sending out reports to instructors on such tiny fractions of their courses.

**Comment by wilcoxbeth** [comment]
It is a bigger problem than just having low N in terms of overall responses.  That will certainly set it off, but I think this will be an issue even in large classes when very few students respond in a particular way.  If the number of students responding 'Agree', for example, is less than 5 even in a large class with a good response rate, that may be enough to make the formula break down when calculating the confidence interval for 'Agree'. 

In terms of sending out individual reports, I know from my experience talking with instructors through the administration process that instructors are going to want reports even if the response rate is low.  We can hardly refuse to provide a report if the instructor wants one.  Perhaps we can include a statement either in the report or in the email cautioning instructors against over-interpreting the report when the response rate is low.

**Comment by mnky9800n** [comment]
This is a reasonable idea. If you write up a statement warning about low N-values I could write a trigger that adds that statement to a report when the matched data is low.

**Comment by mnky9800n** [comment]
I'm assigning this to @wilcoxbeth in case she wants to write up a statement on low n-values that will trigger when matched data is low.

**Comment by wilcoxbeth** [comment]
Here is a little blurb

When the number of matched responses is low (particularly N<10) either due to small class size or poor response rates, we caution against overgeneralizing the E-CLASS results.  In cases of low N, these results can provide valuable insight into that specific group of students' ideas about experimental physics; however, these results may not generalized to the overall student body of physics students.
